# Kubernetes Service template for my-flask-chart
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-flask-chart.fullname" . }} # Generates a unique name for the service
  labels:
    {{- include "my-flask-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }} # e.g., LoadBalancer
  selector:
    app.kubernetes.io/name: {{ include "my-flask-chart.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}       # e.g., 80
      targetPort: {{ .Values.service.targetPort }} # e.g., 5000 (container port)
      name: http
